name = "Greggin"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "770bb037d9ab506fc97a441a734d2b8936949ce36c815258cfc5967a0dae8e17"

[versions]
forge = "47.3.6"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.2"
