 console.log('Hiding items in JEI, pre-event');


JEIEvents.hideItems(event => {
  event.hide('computercraft:turtle_normal')
  event.hide('computercraft:turtle_advanced')
})
EMIEvents.hideItems(event => {
  event.hide('computercraft:turtle_normal')
  event.hide('computercraft:turtle_advanced')
})
REIEvents.hideItems(event => {
  event.hide('computercraft:turtle_normal')
  event.hide('computercraft:turtle_advanced')
})



//Advanced peripherals integration:
JEIEvents.hideItems(event => {
  event.hide('advancedperipherals:computer_tool')
  event.hide('advancedperipherals:chunk_controller')
  event.hide('advancedperipherals:colony_integrator')
  event.hide('advancedperipherals:rs_bridge')
  event.hide('advancedperipherals:energy_detector')
  event.hide('advancedperipherals:block_reader')
  event.hide('advancedperipherals:geo_scanner')
  event.hide('advancedperipherals:peripheral_casing')
  event.hide('advancedperipherals:husbandry_automata_core')
  event.hide('advancedperipherals:end_automata_core')
  event.hide('advancedperipherals:weak_automata_core')
  event.hide('advancedperipherals:overpowered_husbandry_automata_core')
  event.hide('advancedperipherals:overpowered_end_automata_core')
  event.hide('advancedperipherals:overpowered_weak_automata_core')
  event.hide(Item.of("computercraft:pocket_computer_normal").withNBT({Upgrade: "advancedperipherals:colony_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_advanced").withNBT({Upgrade: "advancedperipherals:colony_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_normal").withNBT({Upgrade: "advancedperipherals:geoscanner_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_advanced").withNBT({Upgrade: "advancedperipherals:geoscanner_pocket"}).weakNBT())
})
EMIEvents.hideItems(event => {
  event.hide('advancedperipherals:computer_tool')
  event.hide('advancedperipherals:chunk_controller')
  event.hide('advancedperipherals:colony_integrator')
  event.hide('advancedperipherals:rs_bridge')
  event.hide('advancedperipherals:energy_detector')
  event.hide('advancedperipherals:block_reader')
  event.hide('advancedperipherals:geo_scanner')
  event.hide('advancedperipherals:peripheral_casing')
  event.hide('advancedperipherals:husbandry_automata_core')
  event.hide('advancedperipherals:end_automata_core')
  event.hide('advancedperipherals:weak_automata_core')
  event.hide('advancedperipherals:overpowered_husbandry_automata_core')
  event.hide('advancedperipherals:overpowered_end_automata_core')
  event.hide('advancedperipherals:overpowered_weak_automata_core')
  event.hide(Item.of("computercraft:pocket_computer_normal").withNBT({Upgrade: "advancedperipherals:colony_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_advanced").withNBT({Upgrade: "advancedperipherals:colony_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_normal").withNBT({Upgrade: "advancedperipherals:geoscanner_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_advanced").withNBT({Upgrade: "advancedperipherals:geoscanner_pocket"}).weakNBT())
})
REIEvents.hideItems(event => {
  event.hide('advancedperipherals:computer_tool')
  event.hide('advancedperipherals:chunk_controller')
  event.hide('advancedperipherals:colony_integrator')
  event.hide('advancedperipherals:rs_bridge')
  event.hide('advancedperipherals:energy_detector')
  event.hide('advancedperipherals:block_reader')
  event.hide('advancedperipherals:geo_scanner')
  event.hide('advancedperipherals:peripheral_casing')
  event.hide('advancedperipherals:husbandry_automata_core')
  event.hide('advancedperipherals:end_automata_core')
  event.hide('advancedperipherals:weak_automata_core')
  event.hide('advancedperipherals:overpowered_husbandry_automata_core')
  event.hide('advancedperipherals:overpowered_end_automata_core')
  event.hide('advancedperipherals:overpowered_weak_automata_core')
  event.hide(Item.of("computercraft:pocket_computer_normal").withNBT({Upgrade: "advancedperipherals:colony_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_advanced").withNBT({Upgrade: "advancedperipherals:colony_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_normal").withNBT({Upgrade: "advancedperipherals:geoscanner_pocket"}).weakNBT())
  event.hide(Item.of("computercraft:pocket_computer_advanced").withNBT({Upgrade: "advancedperipherals:geoscanner_pocket"}).weakNBT())
})
