name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - pack.toml
      - unsup.sig
      - .packwizignore
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install packwiz
      uses: ./.github/actions/install-packwiz
    - name: Create a prismlauncher instance
      uses: ./.github/actions/generate-prism-pack
      with:
        outputFile: prismlauncher.zip
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Bundles
        path: |
          prismlauncher.zip